info:
  contact: {}
paths:
  /api/v1/tags:
    post:
      consumes:
      - application/json
      description: 新增标签
      parameters:
      - description: name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":10001,"data":{},"msg":"已存在该标签内容"}'
          schema:
            type: string
      summary: AddTag
      tags:
      - tag
swagger: "2.0"
